#!/bin/zsh
if [ $(amixer get Master | grep -c off) != 2 ]
then
    echo "Volume: ^fg(#bfbfbf)$(expr $(amixer get Master | grep -e "Left.*%" | cut -d'[' -f 2 | cut -d']' -f 1))"
else
    echo "Volume: off "
fi
